### PR TITLE
Predicting using MLJ interface is slow

### PR DESCRIPTION
**Pull request by pat-alt**
@pasq-cat I think we should indeed just go with the direct MLJ interface #121 but for now I would still merge this cause it addresses the compute times.

### CODE REVIEW

**Review by pasq-cat — COMMENTED** [review]
shoudln't the same be done in ```function MLJFlux.predict(model::LaplaceRegression, fitresult, Xnew)```

?

**Comment by pat-alt** [comment]
> shoudln't the same be done in `function MLJFlux.predict(model::LaplaceRegression, fitresult, Xnew)`
> 
> ?

Yes, I've done that

**Comment by pasq-cat** [comment]
> > shoudln't the same be done in `function MLJFlux.predict(model::LaplaceRegression, fitresult, Xnew)`
> > ?
> 
> Yes, I've done that

btw i was sure that laplace accepted vectors as input. has anything been changed or i was wrong the whole time? the documentation says abstractarray but i distinctly remember this requirement....

**Comment by pat-alt** [comment]
> > > shoudln't the same be done in `function MLJFlux.predict(model::LaplaceRegression, fitresult, Xnew)`
> > > ?
> > 
> > 
> > Yes, I've done that
> 
> btw i was sure that laplace accepted vectors as input. has anything been changed or i was wrong the whole time? the documentation says abstractarray but i distinctly remember this requirement....

hmm not sure where you say this https://juliatrustworthyai.github.io/LaplaceRedux.jl/stable/reference/#LaplaceRedux.predict-Tuple{LaplaceRedux.AbstractLaplace,%20AbstractArray}

**Comment by pasq-cat** [comment]
> > > > shoudln't the same be done in `function MLJFlux.predict(model::LaplaceRegression, fitresult, Xnew)`
> > > > ?
> > > 
> > > 
> > > Yes, I've done that
> > 
> > 
> > btw i was sure that laplace accepted vectors as input. has anything been changed or i was wrong the whole time? the documentation says abstractarray but i distinctly remember this requirement....
> 
> hmm not sure where you say this [https://juliatrustworthyai.github.io/LaplaceRedux.jl/stable/reference/#LaplaceRedux.predict-Tuple{LaplaceRedux.AbstractLaplace,%20AbstractArray}](https://juliatrustworthyai.github.io/LaplaceRedux.jl/stable/reference/#LaplaceRedux.predict-Tuple%7BLaplaceRedux.AbstractLaplace,%20AbstractArray%7D)

i know i know, must have been something that  i have misunderstood in the first days, mah

**Pull request merged**
