### PR TITLE
change verbose::Bool  with verbosity::Int

### PR DESCRIPTION
**Pull request by pasq-cat**
as discussed before in #125 .
I storngly suggest to review this pr carefully because the references to ```verbose``` were many  and not all of them used in the same context.

### CODE REVIEW

**Comment by pat-alt** [comment]
Thanks a lot @pasq-cat, I'll try to have a look this week (please ping me again here/Teams/our next meeting if I should forget 😅 )

**Comment by pasq-cat** [comment]
> Thanks a lot @pasq-cat, I'll try to have a look this week (please ping me again here/Teams/our next meeting if I should forget 😅 )

Friendly reminder

**Review by pat-alt — APPROVED** [review]
@pasq-cat looks good to me, although I'm not really sure what's effectively changed here, i.e. isn't this the same as before with `false -> 0` and `true -> >0`?

Maybe I'm missing something

**Comment by pasq-cat** [comment]
@pat-alt  more or less. It's to avoid verbose = verbosity == 0 ? false : true in the interface. I could have just changed verbose in verbosity but once I was changing it I thought that with a direct support to integers in the future you could add multiple level of verbosity. In fact, Mlj adopts this strategy.

**Pull request merged**
